### ISSUE TITLE
Doesn't work with KeePass 2.42

### ISSUE THREAD

**Issue by gjf** [khelmar/KeePassOpenId#4]
This plugin simply doesn't work with KeePass 2.42. Please update it.

**Comment by khelmar** [comment]
Updated. See release https://github.com/khelmar/KeePassOpenId/releases/tag/v1.0.1

**Comment by gjf** [comment]
Don't want to open another ticket - but 2.42.1 released today leads to the same problem.

**Comment by khelmar** [comment]
I'm not seeing any problem with the 2.42.1 update.

**Comment by gjf** [comment]
![Безымянный](https://user-images.githubusercontent.com/322186/57183611-1bbe3980-6eb8-11e9-8e92-c388b6dc5e29.jpg)

Hope it's clear, if not - let me know ann I will provide a translation.
